version: 2

sources:
  - name: dbt_BigQuery_Ravi
    tables:
      - name: patients
      - name: medications
      - name: immunizations
      - name: encounters
      - name: conditions
      - name: careplans
      - name: allergies

models:
  - name: stg_patients
    description: "Staging table for patients."
    columns:
      - name: patient_id
        description: "The unique identifier for a patient."
        tests:
          - not_null
          - unique
      - name: birthdate
        description: "The birthdate of the patient."
      - name: first_name
        description: "The first name of the patient."
      - name: last_name
        description: "The last name of the patient."
      # Add other columns as needed

  - name: stg_medications
    description: "Staging table for medications."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the medication."

  - name: stg_immunizations
    description: "Staging table for immunizations."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the immunization."

  - name: stg_encounters
    description: "Staging table for encounters."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the encounter."

  - name: stg_conditions
    description: "Staging table for conditions."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the condition."

  - name: stg_careplans
    description: "Staging table for care plans."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the care plan."

  - name: stg_allergies
    description: "Staging table for allergies."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the allergy."

  - name: patient_medication_summary
    description: "Summary of patient medications."
    columns:
      - name: patient
        description: "The unique identifier for a patient."
        tests:
          - not_null
      - name: medication_description
        description: "The description of the medication."
      - name: medication_count
        description: "The number of times the medication was prescribed."
      - name: total_medication_cost
        description: "The total cost of the medication."

  - name: patient_encounter_summary
    description: "Summary of patient encounters."
    columns:
      - name: patient
        description: "The unique identifier for a patient."
        tests:
          - not_null
      - name: encounter_count
        description: "The number of encounters the patient had."
      - name: total_encounter_cost
        description: "The total base cost of the encounters."
      - name: total_claim_cost
        description: "The total claim cost of the encounters."

  - name: patient_condition_summary
    description: "Summary of patient conditions."
    columns:
      - name: patient
        description: "The unique identifier for a patient."
        tests:
          - not_null
      - name: condition_count
        description: "The number of conditions the patient has."

  - name: patient_careplan_summary
    description: "Summary of patient care plans."
    columns:
      - name: patient
        description: "The unique identifier for a patient."
        tests:
          - not_null
      - name: careplan_count
        description: "The number of care plans the patient has."

  - name: comprehensive_patient_summary
    description: "Comprehensive summary of patient information, including medications, encounters, conditions, and care plans."
    columns:
      - name: patient_id
        description: "The unique identifier for a patient."
        tests:
          - not_null
          - unique
      - name: first_name
        description: "The first name of the patient."
        tests:
          - not_null
      - name: last_name
        description: "The last name of the patient."
        tests:
          - not_null
      - name: birthdate
        description: "The birthdate of the patient."
     
