version: 2

sources:
  - name: dbt_BigQuery_Ravi
    tables:
      - name: patients
      - name: medications
      - name: immunizations
      - name: encounters
      - name: conditions
      - name: careplans
      - name: allergies

models:
  - name: stg_patients
    description: "Staging table for patients."
    columns:
      - name: patient_id
        description: "The unique identifier for a patient."
        tests:
          - not_null
          - unique
      - name: birthdate
        description: "The birthdate of the patient."
      - name: first_name
        description: "The first name of the patient."
      - name: last_name
        description: "The last name of the patient."
      # Add other columns as needed

  - name: stg_medications
    description: "Staging table for medications."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the medication."

  - name: stg_immunizations
    description: "Staging table for immunizations."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the immunization."

  - name: stg_encounters
    description: "Staging table for encounters."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the encounter."

  - name: stg_conditions
    description: "Staging table for conditions."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the condition."

  - name: stg_careplans
    description: "Staging table for care plans."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the care plan."

  - name: stg_allergies
    description: "Staging table for allergies."
    columns:
      - name: patient
        description: "The unique identifier for the patient."
        tests:
          - not_null
      - name: description
        description: "The description of the allergy."

  - name: patient_clinical_summary
    description: "A summary of patient information combined with clinical data."
    columns:
      - name: patient_id
        description: "The unique identifier for a patient."
        tests:
          - not_null
          - unique
      - name: first_name
        description: "The first name of the patient."
        tests:
          - not_null
      - name: last_name
        description: "The last name of the patient."
        tests:
          - not_null
      - name: birthdate
        description: "The birthdate of the patient."
      - name: gender
        description: "The gender of the patient."
      - name: encounter_description
        description: "Description of the patient's encounters."
      - name: medication_description
        description: "Description of the patient's medications."
      - name: immunization_description
        description: "Description of the patient's immunizations."
      - name: condition_description
        description: "Description of the patient's conditions."
      - name: careplan_description
        description: "Description of the patient's care plans."
      - name: allergy_description
        description: "Description of the patient's allergies."

  - name: enhanced_patient_summary
    description: "An enhanced summary of patient information with additional aggregations."
    columns:
      - name: patient_id
        description: "The unique identifier for a patient."
        tests:
          - not_null
          - unique
      - name: first_name
        description: "The first name of the patient."
      - name: last_name
        description: "The last name of the patient."
      - name: birthdate
        description: "The birthdate of the patient."
      - name: gender
        description: "The gender of the patient."
      - name: encounter_description
        description: "Description of the patient's encounters."
      - name: medication_description
        description: "Description of the patient's medications."
      - name: immunization_description
        description: "Description of the patient's immunizations."
      - name: condition_description
        description: "Description of the patient's conditions."
      - name: careplan_description
        description: "Description of the patient's care plans."
      - name: allergy_description
        description: "Description of the patient's allergies."
      - name: total_encounters
        description: "Total number of unique encounters for the patient."
      - name: total_medications
        description: "Total number of unique medications for the patient."
      - name: total_immunizations
        description: "Total number of unique immunizations for the patient."
      - name: total_conditions
        description: "Total number of unique conditions for the patient."
      - name: total_careplans
        description: "Total number of unique care plans for the patient."
      - name: total_allergies
        description: "Total number of unique allergies for the patient."
